-- ============================================================================
-- BOZZA (NON APPLICARE) — TRANSIZIONE, FASE B: si dimostra la
-- CONCLUSIONE di ciò che era entrato prima della fase A, poi si chiude
-- la porta. Riferimento: PROPOSTA-RECUPERO-REVISIONE.md §5.
-- Stato: DA COLLAUDARE in ambiente isolato con autorizzazione separata.
--
-- La fase B è GUIDATA DA UNO SCRIPT (scripts/collaudo-contratto/
-- passo5-transizione.mjs per il collaudo; il runner di produzione avrà
-- la sua autorizzazione): la CONDIZIONE DI COMPLETAMENTO è un poll
-- FUORI transazione (attendiQuiescenza in strumenti.mjs), la parte
-- transazionale è UNA SOLA transazione generata da costruisciFaseB.
--
-- (B.0) subito DOPO il commit della fase A, lo script registra:
--         t_A  = now() del server (select now())
--         xid_A = pg_current_xact_id_if_assigned()/pg_current_xact_id()
-- (B.1) CONDIZIONE DI COMPLETAMENTO (poll dello script, con timeout e
--       STOP): entrambe le query devono dare zero/vero —
--   select count(*) as pregresse from pg_stat_activity
--     where pid <> pg_backend_pid()
--       and xact_start is not null and xact_start < $T_A$;
--   select pg_snapshot_xmin(pg_current_snapshot())::text::bigint
--            > $XID_A$ as orizzonte_superato;
--       Ogni invocazione legacy vive in una transazione aperta PRIMA di
--       entrare nella funzione: anche sospesa in is_app_member() o
--       prima del primo accesso alle tabelle viene CONTATA finché non
--       conclude. Timeout scaduto → STOP: nulla è cambiato (la fase A
--       resta), si riprova più tardi.
-- (B.2) SOLO a condizione soddisfatta, la TRANSAZIONE UNICA.
--
-- La transazione NON è trascritta qui: viene GENERATA da
-- costruisciFaseB (scripts/collaudo-contratto/strumenti.mjs) — UNICA
-- FONTE, testata in strumenti.test.mjs — e contiene, in UN SOLO
-- begin…commit («o tutto o niente»: un'interruzione non può lasciare
-- le RPC del contratto rivolte ai respingenti):
--
--   · set local lock_timeout = '5s' / statement_timeout = '30s'
--     (STOP, mai attese indefinite né stati a metà);
--   · BARRIERA: lock table family_documents, family_draft_expenses,
--     family_draft_items in access exclusive mode (difesa in
--     profondità; con B.1 soddisfatta si acquisisce subito);
--   · revoke update/insert su bozze e righe, revoke update sui
--     documenti, da authenticated (statement NUOVI: le migrazioni
--     storiche non si toccano);
--   · revoke execute sui CINQUE nomi legacy con le FIRME LETTE DA
--     pg_proc sul progetto bersaglio al momento dell'esecuzione (mai
--     firme trascritte a mano in questa bozza: costruisciFaseB rifiuta
--     una firma mancante) — doppia porta oltre ai respingenti della
--     fase A;
--   · RIPUNTAMENTO degli involucri: i CREATE OR REPLACE di
--     conferma_revisione/scarta_revisione vengono ESTRATTI dalla bozza
--     del contratto (proposte/contratto-revisione.BOZZA.sql) e le
--     chiamate public.conferma_documento(/scarta_documento( diventano
--     private.* — completezza del ripuntamento verificata, niente
--     copie divergenti.

-- (B.3) VERIFICHE POST-COMMIT dello script (tutte, con STOP al primo
--       scostamento): scritture dirette respinte per authenticated
--       (update bozze/righe/documenti, insert bozze/righe); i cinque
--       nomi legacy → P0001 PERCORSO_DISMESSO; chiamata diretta a
--       private.* → permesso negato; flusso 0022 intatto; RPC del
--       contratto funzionanti (giro completo su un documento di prova).
-- ============================================================================
