-- ============================================================================
-- 0042 — CRONOLOGIA DELLE MODIFICHE ALLE PRENOTAZIONI — ***PROPOSTA/BOZZA***
-- ============================================================================
-- STATO: NON APPLICATA. Vive in supabase/proposte/ (incarico del 07/09/2026,
-- pezzo 2): da eseguire a mano nell'editor SQL di Supabase (progetto di
-- PRODUZIONE tnsaa…vwv) con l'autorizzazione di Ania. PRIMA di applicarla il
-- gestionale funziona come oggi: la sezione «Cronologia» in fondo alla scheda
-- prenotazione dice che il registro non è ancora acceso.
--
-- COSA FA
--  1. Tabella public.booking_events: una riga per ogni modifica importante a
--     una prenotazione — camera, date, totale, sconto, pagamento aggiunto o
--     eliminato, annullamento, cambio cliente — con quando, cosa, valore
--     PRIMA e DOPO (jsonb leggibile: nomi di camera e cliente, non solo id).
--  2. Le righe le scrive SOLO il database, con trigger su bookings (after
--     update delle colonne che contano) e su payments (after insert/delete).
--     Il client non scrive mai nel registro: qualunque scrittura passi dalle
--     funzioni sicure dell'app (lib/scritturaSicura, lib/prenotazioneScritture,
--     lib/cambiaCliente) o dalle RPC della proposta 0033 lascia la sua traccia
--     qui, senza che l'app debba ricordarsi di farlo.
--  3. RLS: solo i membri dell'app leggono (private.is_app_member, come la
--     0021/0039); NESSUNO può inserire, modificare o cancellare dal client
--     (grant del solo select ad authenticated). Nessun ripristino automatico:
--     è un registro di sola lettura.
--
-- ROLLBACK: drop trigger if exists bookings_cronologia on public.bookings;
--           drop trigger if exists payments_cronologia on public.payments;
--           drop function if exists public.cronologia_bookings();
--           drop function if exists public.cronologia_payments();
--           drop table if exists public.booking_events;

create table if not exists public.booking_events (
  id uuid primary key default gen_random_uuid(),
  n bigint generated by default as identity,      -- ordine stabile anche a parità di istante (più righe nello stesso update)
  booking_id uuid not null,                       -- nessuna FK: il registro sopravvive alla riga
  soggiorno text not null,                        -- group_id oppure id: tutti i segmenti del soggiorno insieme
  created_at timestamptz not null default now(),
  tipo text not null check (tipo in ('camera', 'date', 'totale', 'sconto', 'pagamento_aggiunto', 'pagamento_eliminato', 'annullamento', 'cliente')),
  prima jsonb,
  dopo jsonb,
  autore uuid default auth.uid()
);
create index if not exists booking_events_soggiorno_idx on public.booking_events (soggiorno, n desc);
create index if not exists booking_events_booking_idx on public.booking_events (booking_id, n desc);

-- 2a. Prenotazioni: una riga per ogni campo importante cambiato nello stesso update
create or replace function public.cronologia_bookings()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_soggiorno text := coalesce(new.group_id::text, new.id::text);
  v_prima text; v_dopo text;
begin
  if new.room_id is distinct from old.room_id then
    select name into v_prima from public.rooms where id = old.room_id;
    select name into v_dopo from public.rooms where id = new.room_id;
    insert into public.booking_events (booking_id, soggiorno, tipo, prima, dopo)
      values (new.id, v_soggiorno, 'camera', jsonb_build_object('camera', v_prima), jsonb_build_object('camera', v_dopo));
  end if;
  if new.check_in is distinct from old.check_in or new.check_out is distinct from old.check_out then
    insert into public.booking_events (booking_id, soggiorno, tipo, prima, dopo)
      values (new.id, v_soggiorno, 'date',
        jsonb_build_object('check_in', old.check_in, 'check_out', old.check_out),
        jsonb_build_object('check_in', new.check_in, 'check_out', new.check_out));
  end if;
  if new.total_amount is distinct from old.total_amount then
    insert into public.booking_events (booking_id, soggiorno, tipo, prima, dopo)
      values (new.id, v_soggiorno, 'totale', jsonb_build_object('totale', old.total_amount), jsonb_build_object('totale', new.total_amount));
  end if;
  if new.discount_type is distinct from old.discount_type or new.discount_value is distinct from old.discount_value then
    insert into public.booking_events (booking_id, soggiorno, tipo, prima, dopo)
      values (new.id, v_soggiorno, 'sconto',
        jsonb_build_object('tipo', old.discount_type, 'valore', old.discount_value),
        jsonb_build_object('tipo', new.discount_type, 'valore', new.discount_value));
  end if;
  if new.status = 'annullata' and old.status is distinct from 'annullata' then
    insert into public.booking_events (booking_id, soggiorno, tipo, prima, dopo)
      values (new.id, v_soggiorno, 'annullamento', jsonb_build_object('stato', old.status), jsonb_build_object('stato', new.status, 'motivo', new.cancelled_reason));
  end if;
  if new.guest_id is distinct from old.guest_id then
    select full_name into v_prima from public.guests where id = old.guest_id;
    select full_name into v_dopo from public.guests where id = new.guest_id;
    insert into public.booking_events (booking_id, soggiorno, tipo, prima, dopo)
      values (new.id, v_soggiorno, 'cliente',
        jsonb_build_object('cliente', v_prima, 'guest_id', old.guest_id),
        jsonb_build_object('cliente', v_dopo, 'guest_id', new.guest_id));
  end if;
  return new;
end;
$$;

drop trigger if exists bookings_cronologia on public.bookings;
create trigger bookings_cronologia
  after update of room_id, check_in, check_out, total_amount, discount_type, discount_value, status, guest_id
  on public.bookings
  for each row execute function public.cronologia_bookings();

-- 2b. Pagamenti: aggiunto (anche dalle RPC segna_pagato / registra_acconto /
--     ricostruisci_incassi della 0033) o eliminato
create or replace function public.cronologia_payments()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_booking uuid := coalesce(new.booking_id, old.booking_id);
  v_soggiorno text;
  v_valore jsonb;
begin
  select coalesce(group_id::text, id::text) into v_soggiorno from public.bookings where id = v_booking;
  if tg_op = 'INSERT' then
    v_valore := jsonb_build_object('importo', new.amount, 'metodo', new.method, 'data', new.paid_on);
    insert into public.booking_events (booking_id, soggiorno, tipo, prima, dopo)
      values (v_booking, coalesce(v_soggiorno, v_booking::text), 'pagamento_aggiunto', null, v_valore);
    return new;
  else
    v_valore := jsonb_build_object('importo', old.amount, 'metodo', old.method, 'data', old.paid_on);
    insert into public.booking_events (booking_id, soggiorno, tipo, prima, dopo)
      values (v_booking, coalesce(v_soggiorno, v_booking::text), 'pagamento_eliminato', v_valore, null);
    return old;
  end if;
end;
$$;

drop trigger if exists payments_cronologia on public.payments;
create trigger payments_cronologia
  after insert or delete on public.payments
  for each row execute function public.cronologia_payments();

-- 3. Sola lettura dal client: RLS, select ai membri dell'app, nient'altro
alter table public.booking_events enable row level security;
revoke all on public.booking_events from public, anon, authenticated;
grant select on public.booking_events to authenticated;
drop policy if exists booking_events_lettura_membri on public.booking_events;
create policy booking_events_lettura_membri on public.booking_events
  for select to authenticated
  using ((select private.is_app_member()));

notify pgrst, 'reload schema';

-- VERIFICA (da controllare dopo Run): tabella con RLS attiva e 1 policy; due trigger
select t.tablename, t.rowsecurity as rls_attiva, count(p.policyname) as policy
  from pg_tables t left join pg_policies p on p.tablename = t.tablename
 where t.schemaname = 'public' and t.tablename = 'booking_events'
 group by t.tablename, t.rowsecurity;
select tgname, tgrelid::regclass as tabella
  from pg_trigger
 where tgname in ('bookings_cronologia', 'payments_cronologia');
